Site/Models/ConstituencyViewModel.cs
using ConstituencyLookup.LookupModels;
using DatabaseModels;
using System.Collections.Generic;
using System.Linq;

namespace Site.Models
{
    public class ConstituencyViewModel
    {
        public ConstituencyResult ConstituencyResult { get; set; }

        public Constituency Constituency { get; set; }

        public string Name => ConstituencyResult.Name;

        public string Postcode => ConstituencyResult.PostCode;

        public List<Candidate> Candidates => Constituency.Candidates.ToList();
    }
}

Site/Models/ErrorViewModel.cs
using System;

namespace Site.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Site/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Site.Models;

namespace Site.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Site/Controllers/VotePledgeController.cs
using Microsoft.AspNetCore.Mvc;
using ConstituencyLookup;
using ConstituencyLookup.LookupModels;
using DataAccess;
using DataAccess.Repositories;
using DatabaseModels;
using Site.Models;
using System.Collections.Generic;

namespace Site.Controllers
{
    public class VotePledgeController : Controller
    {
        private readonly ConstituencyRepository constituencyRepository;

        public VotePledgeController(ElectionContext electionContext)
        {
            this.constituencyRepository = new ConstituencyRepository(electionContext);
        }
        public IActionResult Index(string postcode)
        {
            ConstituencyQuery query = new ConstituencyQuery();
            ConstituencyResult constituencyResult = query.GetConstitutencyByPostCode(postcode);
            
            Constituency constituency = this.constituencyRepository.FindByName(constituencyResult.Name);
            ConstituencyViewModel vm = new ConstituencyViewModel()
            {
                Constituency = constituency,
                ConstituencyResult = constituencyResult,
            };
            return View(vm);
        }

        [HttpGet]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public ActionResult Addresses(string postcode)
        {
            AddressQuery addressQuery = new AddressQuery();
            IEnumerable<AddressResult> addressResults = addressQuery.GetAddressesByPostCode(postcode);
            return Json(addressResults);
        }
    }
}

Site/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to People's pledge</h1>
    <p>Learn about Project Meerkat.</p>
</div>



<div class="row">
    <div class="col-sm-6">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="..." alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Voter's Remain Pledge</h5>
                <p class="card-text">Pledge your vote to a Candidate who will campain for Remaining in the EU</p>
                @using (Html.BeginForm("Index", "VotePledge", null, FormMethod.Post, true, new { @id = "voterpledge-form" }))
                {
                    @Html.TextBox("postcode")
                }

                <a id="voterpledge-submit" href="#" class="btn btn-primary">Pledge My Vote</a>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="..." alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Candidate's Remain Pledge</h5>
                <p class="card-text">Register as candidate who will sign a binding pledge to campaign to Remain in the EU</p>
                <a href="#" class="btn btn-primary">Pledge To Remain</a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
        $(function () {
            $("#voterpledge-submit").click(function () {
                $("#voterpledge-form").submit();
                return false;
            });
        });
</script>

Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Site</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Site</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Site - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react/16.8.0/umd/react.development.js"></script>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.0/umd/react-dom.development.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Site/Views/VotePledge/Index.cshtml
@model Site.Models.ConstituencyViewModel

@{
    ViewData["Title"] = "Pledge My Vote";
}

@section Scripts{
    <script src="@Url.Content("~/js/react/AddressPicker.jsx")"></script>
    <script src="@Url.Content("~/js/react/VotePledgeIndex.jsx")"></script>
}

<h1>Pledge My Vote</h1>

<div>
    <h4>Use this form to decide which candidate you will pledge your vote to</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Postcode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Postcode)
        </dd>
    </dl>
    <table class="table table-hover">
        <thead class="thead-light">
            <tr>
                <th scope="col">Candidate</th>
                <th scope="col">Party</th>
                <th scope="col">Tweet to</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var candidate in Model.Candidates)
            {
                <tr>
                    <th scope="row">
                        @candidate.Name
                    </th>
                    <td>
                        @candidate.Party.Name
                    </td>
                    <td>
                        @if (!string.IsNullOrWhiteSpace(candidate.TwitterUsername))
                        {
                            <a href="https://twitter.com/intent/tweet?screen_name=@candidate.TwitterUsername&ref_src=twsrc%5Etfw" class="twitter-mention-button" data-show-count="false">Tweet to @candidate.TwitterUsername</a>
                            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <hr />
    <div id="content"></div>
</div>